// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: customer.proto

package customerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Customer represents a customer in the system
type Customer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerNumber string                 `protobuf:"bytes,2,opt,name=customer_number,json=customerNumber,proto3" json:"customer_number,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName     string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName       string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Email          string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Phone          string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedBy      string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	UpdatedBy      string                 `protobuf:"bytes,13,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Version        int32                  `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_customer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetCustomerNumber() string {
	if x != nil {
		return x.CustomerNumber
	}
	return ""
}

func (x *Customer) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Customer) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *Customer) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Customer) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Customer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Customer) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Customer) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Customer) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// Address represents a customer's address
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AddressType   string                 `protobuf:"bytes,3,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	Street1       string                 `protobuf:"bytes,4,opt,name=street1,proto3" json:"street1,omitempty"`
	Street2       string                 `protobuf:"bytes,5,opt,name=street2,proto3" json:"street2,omitempty"`
	City          string                 `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,8,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,10,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_customer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Address) GetAddressType() string {
	if x != nil {
		return x.AddressType
	}
	return ""
}

func (x *Address) GetStreet1() string {
	if x != nil {
		return x.Street1
	}
	return ""
}

func (x *Address) GetStreet2() string {
	if x != nil {
		return x.Street2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Address) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *Address) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Document represents a customer's identification document
type Document struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId         string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DocumentType       string                 `protobuf:"bytes,3,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentNumber     string                 `protobuf:"bytes,4,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"` // Encrypted in transit
	IssuingAuthority   string                 `protobuf:"bytes,5,opt,name=issuing_authority,json=issuingAuthority,proto3" json:"issuing_authority,omitempty"`
	IssuingCountry     string                 `protobuf:"bytes,6,opt,name=issuing_country,json=issuingCountry,proto3" json:"issuing_country,omitempty"`
	IssueDate          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpiryDate         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	VerificationStatus string                 `protobuf:"bytes,9,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
	VerifiedAt         *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=verified_at,json=verifiedAt,proto3" json:"verified_at,omitempty"`
	VerifiedBy         string                 `protobuf:"bytes,11,opt,name=verified_by,json=verifiedBy,proto3" json:"verified_by,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_customer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{2}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Document) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *Document) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *Document) GetIssuingAuthority() string {
	if x != nil {
		return x.IssuingAuthority
	}
	return ""
}

func (x *Document) GetIssuingCountry() string {
	if x != nil {
		return x.IssuingCountry
	}
	return ""
}

func (x *Document) GetIssueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssueDate
	}
	return nil
}

func (x *Document) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *Document) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

func (x *Document) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *Document) GetVerifiedBy() string {
	if x != nil {
		return x.VerifiedBy
	}
	return ""
}

func (x *Document) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Document) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// StatusChange records a customer status change
type StatusChange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId     string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	PreviousStatus string                 `protobuf:"bytes,3,opt,name=previous_status,json=previousStatus,proto3" json:"previous_status,omitempty"`
	NewStatus      string                 `protobuf:"bytes,4,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	Reason         string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedBy      string                 `protobuf:"bytes,6,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	ChangedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatusChange) Reset() {
	*x = StatusChange{}
	mi := &file_customer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusChange) ProtoMessage() {}

func (x *StatusChange) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusChange.ProtoReflect.Descriptor instead.
func (*StatusChange) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{3}
}

func (x *StatusChange) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusChange) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *StatusChange) GetPreviousStatus() string {
	if x != nil {
		return x.PreviousStatus
	}
	return ""
}

func (x *StatusChange) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *StatusChange) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StatusChange) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

func (x *StatusChange) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

// CreateCustomerRequest is the request for creating a customer
type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName    string                 `protobuf:"bytes,2,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	TaxId         string                 `protobuf:"bytes,5,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"` // Encrypted in transit
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,8,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_customer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateCustomerRequest) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *CreateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateCustomerRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *CreateCustomerRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

// CreateCustomerResponse is the response for creating a customer
type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_customer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

// GetCustomerRequest is the request for getting a customer
type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_customer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{6}
}

func (x *GetCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetCustomerResponse is the response for getting a customer
type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_customer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{7}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

// UpdateCustomerRequest is the request for updating a customer
type UpdateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName    string                 `protobuf:"bytes,3,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName      string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	DateOfBirth   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	TaxId         string                 `protobuf:"bytes,6,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"` // Encrypted in transit
	Email         string                 `protobuf:"bytes,7,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,9,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Version       int32                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerRequest) Reset() {
	*x = UpdateCustomerRequest{}
	mi := &file_customer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRequest) ProtoMessage() {}

func (x *UpdateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCustomerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCustomerRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *UpdateCustomerRequest) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *UpdateCustomerRequest) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *UpdateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateCustomerRequest) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *UpdateCustomerRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

// UpdateCustomerResponse is the response for updating a customer
type UpdateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerResponse) Reset() {
	*x = UpdateCustomerResponse{}
	mi := &file_customer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerResponse) ProtoMessage() {}

func (x *UpdateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

// SearchCustomersRequest is the request for searching customers
type SearchCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	FromDate      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Limit         int32                  `protobuf:"varint,8,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,9,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCustomersRequest) Reset() {
	*x = SearchCustomersRequest{}
	mi := &file_customer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCustomersRequest) ProtoMessage() {}

func (x *SearchCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCustomersRequest.ProtoReflect.Descriptor instead.
func (*SearchCustomersRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{10}
}

func (x *SearchCustomersRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *SearchCustomersRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *SearchCustomersRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SearchCustomersRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *SearchCustomersRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchCustomersRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *SearchCustomersRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *SearchCustomersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchCustomersRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// SearchCustomersResponse is the response for searching customers
type SearchCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchCustomersResponse) Reset() {
	*x = SearchCustomersResponse{}
	mi := &file_customer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchCustomersResponse) ProtoMessage() {}

func (x *SearchCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchCustomersResponse.ProtoReflect.Descriptor instead.
func (*SearchCustomersResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{11}
}

func (x *SearchCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

func (x *SearchCustomersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// AddAddressRequest is the request for adding an address
type AddAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AddressType   string                 `protobuf:"bytes,2,opt,name=address_type,json=addressType,proto3" json:"address_type,omitempty"`
	Street1       string                 `protobuf:"bytes,3,opt,name=street1,proto3" json:"street1,omitempty"`
	Street2       string                 `protobuf:"bytes,4,opt,name=street2,proto3" json:"street2,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode    string                 `protobuf:"bytes,7,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Country       string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,9,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	ValidFrom     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_from,json=validFrom,proto3" json:"valid_from,omitempty"`
	ValidTo       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=valid_to,json=validTo,proto3" json:"valid_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddressRequest) Reset() {
	*x = AddAddressRequest{}
	mi := &file_customer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressRequest) ProtoMessage() {}

func (x *AddAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressRequest.ProtoReflect.Descriptor instead.
func (*AddAddressRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{12}
}

func (x *AddAddressRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddAddressRequest) GetAddressType() string {
	if x != nil {
		return x.AddressType
	}
	return ""
}

func (x *AddAddressRequest) GetStreet1() string {
	if x != nil {
		return x.Street1
	}
	return ""
}

func (x *AddAddressRequest) GetStreet2() string {
	if x != nil {
		return x.Street2
	}
	return ""
}

func (x *AddAddressRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *AddAddressRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AddAddressRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *AddAddressRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *AddAddressRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *AddAddressRequest) GetValidFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidFrom
	}
	return nil
}

func (x *AddAddressRequest) GetValidTo() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidTo
	}
	return nil
}

// AddAddressResponse is the response for adding an address
type AddAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       *Address               `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAddressResponse) Reset() {
	*x = AddAddressResponse{}
	mi := &file_customer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAddressResponse) ProtoMessage() {}

func (x *AddAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAddressResponse.ProtoReflect.Descriptor instead.
func (*AddAddressResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{13}
}

func (x *AddAddressResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// AddDocumentRequest is the request for adding a document
type AddDocumentRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CustomerId       string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	DocumentType     string                 `protobuf:"bytes,2,opt,name=document_type,json=documentType,proto3" json:"document_type,omitempty"`
	DocumentNumber   string                 `protobuf:"bytes,3,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"` // Encrypted in transit
	IssuingAuthority string                 `protobuf:"bytes,4,opt,name=issuing_authority,json=issuingAuthority,proto3" json:"issuing_authority,omitempty"`
	IssuingCountry   string                 `protobuf:"bytes,5,opt,name=issuing_country,json=issuingCountry,proto3" json:"issuing_country,omitempty"`
	IssueDate        *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpiryDate       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddDocumentRequest) Reset() {
	*x = AddDocumentRequest{}
	mi := &file_customer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentRequest) ProtoMessage() {}

func (x *AddDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentRequest.ProtoReflect.Descriptor instead.
func (*AddDocumentRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{14}
}

func (x *AddDocumentRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AddDocumentRequest) GetDocumentType() string {
	if x != nil {
		return x.DocumentType
	}
	return ""
}

func (x *AddDocumentRequest) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *AddDocumentRequest) GetIssuingAuthority() string {
	if x != nil {
		return x.IssuingAuthority
	}
	return ""
}

func (x *AddDocumentRequest) GetIssuingCountry() string {
	if x != nil {
		return x.IssuingCountry
	}
	return ""
}

func (x *AddDocumentRequest) GetIssueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssueDate
	}
	return nil
}

func (x *AddDocumentRequest) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

// AddDocumentResponse is the response for adding a document
type AddDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Document      *Document              `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddDocumentResponse) Reset() {
	*x = AddDocumentResponse{}
	mi := &file_customer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDocumentResponse) ProtoMessage() {}

func (x *AddDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDocumentResponse.ProtoReflect.Descriptor instead.
func (*AddDocumentResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{15}
}

func (x *AddDocumentResponse) GetDocument() *Document {
	if x != nil {
		return x.Document
	}
	return nil
}

// UpdateCustomerStatusRequest is the request for updating customer status
type UpdateCustomerStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	NewStatus     string                 `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ChangedBy     string                 `protobuf:"bytes,4,opt,name=changed_by,json=changedBy,proto3" json:"changed_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerStatusRequest) Reset() {
	*x = UpdateCustomerStatusRequest{}
	mi := &file_customer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerStatusRequest) ProtoMessage() {}

func (x *UpdateCustomerStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerStatusRequest) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateCustomerStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCustomerStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *UpdateCustomerStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateCustomerStatusRequest) GetChangedBy() string {
	if x != nil {
		return x.ChangedBy
	}
	return ""
}

// UpdateCustomerStatusResponse is the response for updating customer status
type UpdateCustomerStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	StatusChange  *StatusChange          `protobuf:"bytes,2,opt,name=status_change,json=statusChange,proto3" json:"status_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerStatusResponse) Reset() {
	*x = UpdateCustomerStatusResponse{}
	mi := &file_customer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerStatusResponse) ProtoMessage() {}

func (x *UpdateCustomerStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomerStatusResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateCustomerStatusResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *UpdateCustomerStatusResponse) GetStatusChange() *StatusChange {
	if x != nil {
		return x.StatusChange
	}
	return nil
}

// CustomerFullProfileResponse contains the complete customer profile
type CustomerFullProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Documents     []*Document            `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	StatusHistory []*StatusChange        `protobuf:"bytes,4,rep,name=status_history,json=statusHistory,proto3" json:"status_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomerFullProfileResponse) Reset() {
	*x = CustomerFullProfileResponse{}
	mi := &file_customer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerFullProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerFullProfileResponse) ProtoMessage() {}

func (x *CustomerFullProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_customer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerFullProfileResponse.ProtoReflect.Descriptor instead.
func (*CustomerFullProfileResponse) Descriptor() ([]byte, []int) {
	return file_customer_proto_rawDescGZIP(), []int{18}
}

func (x *CustomerFullProfileResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *CustomerFullProfileResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *CustomerFullProfileResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *CustomerFullProfileResponse) GetStatusHistory() []*StatusChange {
	if x != nil {
		return x.StatusHistory
	}
	return nil
}

var File_customer_proto protoreflect.FileDescriptor

const file_customer_proto_rawDesc = "" +
	"\n" +
	"\x0ecustomer.proto\x12\vcustomer.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x03\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fcustomer_number\x18\x02 \x01(\tR\x0ecustomerNumber\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vmiddle_name\x18\x04 \x01(\tR\n" +
	"middleName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\x12\x1d\n" +
	"\n" +
	"updated_by\x18\r \x01(\tR\tupdatedBy\x12\x18\n" +
	"\aversion\x18\x0e \x01(\x05R\aversion\"\xfd\x03\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\faddress_type\x18\x03 \x01(\tR\vaddressType\x12\x18\n" +
	"\astreet1\x18\x04 \x01(\tR\astreet1\x12\x18\n" +
	"\astreet2\x18\x05 \x01(\tR\astreet2\x12\x12\n" +
	"\x04city\x18\x06 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\b \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\t \x01(\tR\acountry\x12\x1d\n" +
	"\n" +
	"is_primary\x18\n" +
	" \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"valid_from\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xdc\x04\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rdocument_type\x18\x03 \x01(\tR\fdocumentType\x12'\n" +
	"\x0fdocument_number\x18\x04 \x01(\tR\x0edocumentNumber\x12+\n" +
	"\x11issuing_authority\x18\x05 \x01(\tR\x10issuingAuthority\x12'\n" +
	"\x0fissuing_country\x18\x06 \x01(\tR\x0eissuingCountry\x129\n" +
	"\n" +
	"issue_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tissueDate\x12;\n" +
	"\vexpiry_date\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12/\n" +
	"\x13verification_status\x18\t \x01(\tR\x12verificationStatus\x12;\n" +
	"\vverified_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"verifiedAt\x12\x1f\n" +
	"\vverified_by\x18\v \x01(\tR\n" +
	"verifiedBy\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf9\x01\n" +
	"\fStatusChange\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12'\n" +
	"\x0fprevious_status\x18\x03 \x01(\tR\x0epreviousStatus\x12\x1d\n" +
	"\n" +
	"new_status\x18\x04 \x01(\tR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x06 \x01(\tR\tchangedBy\x129\n" +
	"\n" +
	"changed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\x96\x02\n" +
	"\x15CreateCustomerRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vmiddle_name\x18\x02 \x01(\tR\n" +
	"middleName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x15\n" +
	"\x06tax_id\x18\x05 \x01(\tR\x05taxId\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\a \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"created_by\x18\b \x01(\tR\tcreatedBy\"K\n" +
	"\x16CreateCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"$\n" +
	"\x12GetCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x13GetCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"\xc0\x02\n" +
	"\x15UpdateCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1f\n" +
	"\vmiddle_name\x18\x03 \x01(\tR\n" +
	"middleName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12>\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x15\n" +
	"\x06tax_id\x18\x06 \x01(\tR\x05taxId\x12\x14\n" +
	"\x05email\x18\a \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\b \x01(\tR\x05phone\x12\x1d\n" +
	"\n" +
	"updated_by\x18\t \x01(\tR\tupdatedBy\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x05R\aversion\"K\n" +
	"\x16UpdateCustomerResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\"\xb4\x02\n" +
	"\x16SearchCustomersRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x127\n" +
	"\tfrom_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12\x14\n" +
	"\x05limit\x18\b \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\t \x01(\x05R\x06offset\"d\n" +
	"\x17SearchCustomersResponse\x123\n" +
	"\tcustomers\x18\x01 \x03(\v2\x15.customer.v1.CustomerR\tcustomers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x81\x03\n" +
	"\x11AddAddressRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\faddress_type\x18\x02 \x01(\tR\vaddressType\x12\x18\n" +
	"\astreet1\x18\x03 \x01(\tR\astreet1\x12\x18\n" +
	"\astreet2\x18\x04 \x01(\tR\astreet2\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x06 \x01(\tR\x05state\x12\x1f\n" +
	"\vpostal_code\x18\a \x01(\tR\n" +
	"postalCode\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x1d\n" +
	"\n" +
	"is_primary\x18\t \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"valid_from\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tvalidFrom\x125\n" +
	"\bvalid_to\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\avalidTo\"D\n" +
	"\x12AddAddressResponse\x12.\n" +
	"\aaddress\x18\x01 \x01(\v2\x14.customer.v1.AddressR\aaddress\"\xd1\x02\n" +
	"\x12AddDocumentRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rdocument_type\x18\x02 \x01(\tR\fdocumentType\x12'\n" +
	"\x0fdocument_number\x18\x03 \x01(\tR\x0edocumentNumber\x12+\n" +
	"\x11issuing_authority\x18\x04 \x01(\tR\x10issuingAuthority\x12'\n" +
	"\x0fissuing_country\x18\x05 \x01(\tR\x0eissuingCountry\x129\n" +
	"\n" +
	"issue_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tissueDate\x12;\n" +
	"\vexpiry_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\"H\n" +
	"\x13AddDocumentResponse\x121\n" +
	"\bdocument\x18\x01 \x01(\v2\x15.customer.v1.DocumentR\bdocument\"\x83\x01\n" +
	"\x1bUpdateCustomerStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"new_status\x18\x02 \x01(\tR\tnewStatus\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"changed_by\x18\x04 \x01(\tR\tchangedBy\"\x91\x01\n" +
	"\x1cUpdateCustomerStatusResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\x12>\n" +
	"\rstatus_change\x18\x02 \x01(\v2\x19.customer.v1.StatusChangeR\fstatusChange\"\xfb\x01\n" +
	"\x1bCustomerFullProfileResponse\x121\n" +
	"\bcustomer\x18\x01 \x01(\v2\x15.customer.v1.CustomerR\bcustomer\x122\n" +
	"\taddresses\x18\x02 \x03(\v2\x14.customer.v1.AddressR\taddresses\x123\n" +
	"\tdocuments\x18\x03 \x03(\v2\x15.customer.v1.DocumentR\tdocuments\x12@\n" +
	"\x0estatus_history\x18\x04 \x03(\v2\x19.customer.v1.StatusChangeR\rstatusHistory2\xea\x05\n" +
	"\x0fCustomerService\x12Y\n" +
	"\x0eCreateCustomer\x12\".customer.v1.CreateCustomerRequest\x1a#.customer.v1.CreateCustomerResponse\x12P\n" +
	"\vGetCustomer\x12\x1f.customer.v1.GetCustomerRequest\x1a .customer.v1.GetCustomerResponse\x12Y\n" +
	"\x0eUpdateCustomer\x12\".customer.v1.UpdateCustomerRequest\x1a#.customer.v1.UpdateCustomerResponse\x12\\\n" +
	"\x0fSearchCustomers\x12#.customer.v1.SearchCustomersRequest\x1a$.customer.v1.SearchCustomersResponse\x12M\n" +
	"\n" +
	"AddAddress\x12\x1e.customer.v1.AddAddressRequest\x1a\x1f.customer.v1.AddAddressResponse\x12P\n" +
	"\vAddDocument\x12\x1f.customer.v1.AddDocumentRequest\x1a .customer.v1.AddDocumentResponse\x12k\n" +
	"\x14UpdateCustomerStatus\x12(.customer.v1.UpdateCustomerStatusRequest\x1a).customer.v1.UpdateCustomerStatusResponse\x12c\n" +
	"\x16GetCustomerFullProfile\x12\x1f.customer.v1.GetCustomerRequest\x1a(.customer.v1.CustomerFullProfileResponseBMZKgithub.com/core-banking/services/customer-service/internal/proto/customerpbb\x06proto3"

var (
	file_customer_proto_rawDescOnce sync.Once
	file_customer_proto_rawDescData []byte
)

func file_customer_proto_rawDescGZIP() []byte {
	file_customer_proto_rawDescOnce.Do(func() {
		file_customer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_customer_proto_rawDesc), len(file_customer_proto_rawDesc)))
	})
	return file_customer_proto_rawDescData
}

var file_customer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_customer_proto_goTypes = []any{
	(*Customer)(nil),                     // 0: customer.v1.Customer
	(*Address)(nil),                      // 1: customer.v1.Address
	(*Document)(nil),                     // 2: customer.v1.Document
	(*StatusChange)(nil),                 // 3: customer.v1.StatusChange
	(*CreateCustomerRequest)(nil),        // 4: customer.v1.CreateCustomerRequest
	(*CreateCustomerResponse)(nil),       // 5: customer.v1.CreateCustomerResponse
	(*GetCustomerRequest)(nil),           // 6: customer.v1.GetCustomerRequest
	(*GetCustomerResponse)(nil),          // 7: customer.v1.GetCustomerResponse
	(*UpdateCustomerRequest)(nil),        // 8: customer.v1.UpdateCustomerRequest
	(*UpdateCustomerResponse)(nil),       // 9: customer.v1.UpdateCustomerResponse
	(*SearchCustomersRequest)(nil),       // 10: customer.v1.SearchCustomersRequest
	(*SearchCustomersResponse)(nil),      // 11: customer.v1.SearchCustomersResponse
	(*AddAddressRequest)(nil),            // 12: customer.v1.AddAddressRequest
	(*AddAddressResponse)(nil),           // 13: customer.v1.AddAddressResponse
	(*AddDocumentRequest)(nil),           // 14: customer.v1.AddDocumentRequest
	(*AddDocumentResponse)(nil),          // 15: customer.v1.AddDocumentResponse
	(*UpdateCustomerStatusRequest)(nil),  // 16: customer.v1.UpdateCustomerStatusRequest
	(*UpdateCustomerStatusResponse)(nil), // 17: customer.v1.UpdateCustomerStatusResponse
	(*CustomerFullProfileResponse)(nil),  // 18: customer.v1.CustomerFullProfileResponse
	(*timestamppb.Timestamp)(nil),        // 19: google.protobuf.Timestamp
}
var file_customer_proto_depIdxs = []int32{
	19, // 0: customer.v1.Customer.date_of_birth:type_name -> google.protobuf.Timestamp
	19, // 1: customer.v1.Customer.created_at:type_name -> google.protobuf.Timestamp
	19, // 2: customer.v1.Customer.updated_at:type_name -> google.protobuf.Timestamp
	19, // 3: customer.v1.Address.valid_from:type_name -> google.protobuf.Timestamp
	19, // 4: customer.v1.Address.valid_to:type_name -> google.protobuf.Timestamp
	19, // 5: customer.v1.Address.created_at:type_name -> google.protobuf.Timestamp
	19, // 6: customer.v1.Address.updated_at:type_name -> google.protobuf.Timestamp
	19, // 7: customer.v1.Document.issue_date:type_name -> google.protobuf.Timestamp
	19, // 8: customer.v1.Document.expiry_date:type_name -> google.protobuf.Timestamp
	19, // 9: customer.v1.Document.verified_at:type_name -> google.protobuf.Timestamp
	19, // 10: customer.v1.Document.created_at:type_name -> google.protobuf.Timestamp
	19, // 11: customer.v1.Document.updated_at:type_name -> google.protobuf.Timestamp
	19, // 12: customer.v1.StatusChange.changed_at:type_name -> google.protobuf.Timestamp
	19, // 13: customer.v1.CreateCustomerRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	0,  // 14: customer.v1.CreateCustomerResponse.customer:type_name -> customer.v1.Customer
	0,  // 15: customer.v1.GetCustomerResponse.customer:type_name -> customer.v1.Customer
	19, // 16: customer.v1.UpdateCustomerRequest.date_of_birth:type_name -> google.protobuf.Timestamp
	0,  // 17: customer.v1.UpdateCustomerResponse.customer:type_name -> customer.v1.Customer
	19, // 18: customer.v1.SearchCustomersRequest.from_date:type_name -> google.protobuf.Timestamp
	19, // 19: customer.v1.SearchCustomersRequest.to_date:type_name -> google.protobuf.Timestamp
	0,  // 20: customer.v1.SearchCustomersResponse.customers:type_name -> customer.v1.Customer
	19, // 21: customer.v1.AddAddressRequest.valid_from:type_name -> google.protobuf.Timestamp
	19, // 22: customer.v1.AddAddressRequest.valid_to:type_name -> google.protobuf.Timestamp
	1,  // 23: customer.v1.AddAddressResponse.address:type_name -> customer.v1.Address
	19, // 24: customer.v1.AddDocumentRequest.issue_date:type_name -> google.protobuf.Timestamp
	19, // 25: customer.v1.AddDocumentRequest.expiry_date:type_name -> google.protobuf.Timestamp
	2,  // 26: customer.v1.AddDocumentResponse.document:type_name -> customer.v1.Document
	0,  // 27: customer.v1.UpdateCustomerStatusResponse.customer:type_name -> customer.v1.Customer
	3,  // 28: customer.v1.UpdateCustomerStatusResponse.status_change:type_name -> customer.v1.StatusChange
	0,  // 29: customer.v1.CustomerFullProfileResponse.customer:type_name -> customer.v1.Customer
	1,  // 30: customer.v1.CustomerFullProfileResponse.addresses:type_name -> customer.v1.Address
	2,  // 31: customer.v1.CustomerFullProfileResponse.documents:type_name -> customer.v1.Document
	3,  // 32: customer.v1.CustomerFullProfileResponse.status_history:type_name -> customer.v1.StatusChange
	4,  // 33: customer.v1.CustomerService.CreateCustomer:input_type -> customer.v1.CreateCustomerRequest
	6,  // 34: customer.v1.CustomerService.GetCustomer:input_type -> customer.v1.GetCustomerRequest
	8,  // 35: customer.v1.CustomerService.UpdateCustomer:input_type -> customer.v1.UpdateCustomerRequest
	10, // 36: customer.v1.CustomerService.SearchCustomers:input_type -> customer.v1.SearchCustomersRequest
	12, // 37: customer.v1.CustomerService.AddAddress:input_type -> customer.v1.AddAddressRequest
	14, // 38: customer.v1.CustomerService.AddDocument:input_type -> customer.v1.AddDocumentRequest
	16, // 39: customer.v1.CustomerService.UpdateCustomerStatus:input_type -> customer.v1.UpdateCustomerStatusRequest
	6,  // 40: customer.v1.CustomerService.GetCustomerFullProfile:input_type -> customer.v1.GetCustomerRequest
	5,  // 41: customer.v1.CustomerService.CreateCustomer:output_type -> customer.v1.CreateCustomerResponse
	7,  // 42: customer.v1.CustomerService.GetCustomer:output_type -> customer.v1.GetCustomerResponse
	9,  // 43: customer.v1.CustomerService.UpdateCustomer:output_type -> customer.v1.UpdateCustomerResponse
	11, // 44: customer.v1.CustomerService.SearchCustomers:output_type -> customer.v1.SearchCustomersResponse
	13, // 45: customer.v1.CustomerService.AddAddress:output_type -> customer.v1.AddAddressResponse
	15, // 46: customer.v1.CustomerService.AddDocument:output_type -> customer.v1.AddDocumentResponse
	17, // 47: customer.v1.CustomerService.UpdateCustomerStatus:output_type -> customer.v1.UpdateCustomerStatusResponse
	18, // 48: customer.v1.CustomerService.GetCustomerFullProfile:output_type -> customer.v1.CustomerFullProfileResponse
	41, // [41:49] is the sub-list for method output_type
	33, // [33:41] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_customer_proto_init() }
func file_customer_proto_init() {
	if File_customer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_customer_proto_rawDesc), len(file_customer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_customer_proto_goTypes,
		DependencyIndexes: file_customer_proto_depIdxs,
		MessageInfos:      file_customer_proto_msgTypes,
	}.Build()
	File_customer_proto = out.File
	file_customer_proto_goTypes = nil
	file_customer_proto_depIdxs = nil
}
